USE DB_VENDAS

-- OPERADORES ESCALERES =, != <>, >=, >, <, <=

-- FUNCIONÁRIOS QUE GANHAM MENOS QUE R$ 1000
SELECT * FROM TB_EMPREGADO
WHERE SALARIO < 1000

-- TODOS OS CLIENTES DO ESTADO DE SP
SELECT CODCLI, NOME FROM TB_CLIENTE
WHERE ESTADO = 'SP'

-- PEDIDOS (VENDAS) REALIZADOS DEPOIS DE 2018 (NÃO CONSIDERAR PEDIDOS DE 2018)
SELECT * FROM TB_PEDIDO
WHERE DATA_EMISSAO > '2018-12-31 23:59:59'

SELECT * FROM TB_PEDIDO
WHERE DATA_EMISSAO >= '2019-01-01'

-- OPERADORES LÓGICOS AND, OR, NOT

-- CLIENTES DE SP OU RJ
SELECT NOME, ESTADO FROM TB_CLIENTE
WHERE ESTADO = 'SP' OR ESTADO = 'RJ'

-- EMPREGADOS DO DEPARTAMENTO 5 QUE GANHAM MENOS DE 1200 
SELECT * FROM TB_EMPREGADO
WHERE COD_DEPTO = 5 AND SALARIO < 1200

-- RETIRAR DO SELECT OS EMPREGADOS DO DEPARTAMENTO 5 QUE GANHAM MENOS DE 1200 
SELECT * FROM TB_EMPREGADO
WHERE NOT (COD_DEPTO = 5 AND SALARIO < 1200)
ORDER BY CODFUN

SELECT * FROM TB_EMPREGADO
WHERE COD_DEPTO != 5 OR SALARIO >= 1200
ORDER BY CODFUN

-- OPERADORES PREDICADOS IN / BETWEEN - NOT IN / NOT BETWEEN

-- CLIENTES DE SP, RJ, MG, ES
SELECT NOME, ESTADO FROM TB_CLIENTE
WHERE ESTADO = 'SP' OR ESTADO = 'RJ' OR ESTADO = 'MG' OR ESTADO = 'ES'

SELECT NOME, ESTADO FROM TB_CLIENTE
WHERE ESTADO IN ('SP','RJ','MG','ES')


-- PRODUTOS QUE NÃO SEJAM DOS TIPOS 1,2,3,4,5
SELECT * FROM TB_PRODUTO
WHERE COD_TIPO != 1 AND COD_TIPO != 2 AND COD_TIPO != 3 AND COD_TIPO != 4 AND COD_TIPO != 5
ORDER BY COD_TIPO

SELECT * FROM TB_PRODUTO
WHERE COD_TIPO NOT IN (1,2,3,4,5)
ORDER BY COD_TIPO

-- TODOS PEDIDOS DE 2017
SELECT * FROM TB_PEDIDO
WHERE DATA_EMISSAO >= '20170101' AND DATA_EMISSAO <= '20171231 23:59:59'

SELECT * FROM TB_PEDIDO
WHERE DATA_EMISSAO BETWEEN '20170101' AND '20171231 23:59:59'

-- TODOS OS EMPREGADOS COM CÓDIGO DE DEPARTAMENTO INFERIOR A 5 OU SUPERIOR A 9
SELECT * FROM TB_EMPREGADO
WHERE COD_DEPTO < 5 OR COD_DEPTO > 9
ORDER BY COD_DEPTO

SELECT * FROM TB_EMPREGADO
WHERE COD_DEPTO NOT BETWEEN 5 AND 9 
ORDER BY COD_DEPTO

-- CARACTERES CORINGAS %,_, []

-- EMPREGADOS COM NOME MARIA
SELECT * FROM TB_EMPREGADO
WHERE NOME = 'MARIA'

-- EMPREGADOS QUE O NOME INICIE COM MARIA
SELECT * FROM TB_EMPREGADO
WHERE NOME LIKE 'MARIA%'

SELECT * FROM TB_EMPREGADO
WHERE NOME LIKE 'MARIA %'	
				
-- EMPREGADOS QUE O NOME TERMINE COM MARIA
SELECT * FROM TB_EMPREGADO
WHERE NOME LIKE '%MARIA'

-- EMPREGADO COM NOME QUE CONTENHA JUNIOR
SELECT * FROM TB_EMPREGADO
WHERE NOME LIKE '%JUNIOR%'

-- EMPREGADOS COM NOME QUE CONTENHA SOUZA OU SOUSA		
SELECT * FROM TB_EMPREGADO
WHERE NOME LIKE '%SOUZA%' OR NOME LIKE '%SOUSA%' 

SELECT * FROM TB_EMPREGADO
WHERE NOME LIKE '%SOU[ZS]A%'

-- EMPREGADOS COM NOME DE JOSÉ OU JOSE
SELECT * FROM TB_EMPREGADO
WHERE NOME LIKE '%JOS[ÉE]%'

-- TODOS FUNCIONÁRIOS QUE NOME TENHAM A SEGUNDA LETRA A
SELECT * FROM TB_EMPREGADO
WHERE NOME LIKE '_a%'

-- TODOS OS CLIENTES DAS CIDADES QUE TERMINEM COM A
SELECT * FROM TB_CLIENTE
WHERE CIDADE LIKE '%A'

-- TODOS OS CLIENTES DAS CIDADES QUE TERMINEM COM A E COMECEM COM UMA VOGAL
SELECT * FROM TB_CLIENTE
WHERE CIDADE LIKE '[aeiou]%A'

-- TODOS OS CLIENTES DAS CIDADES QUE TERMINEM COM A, COMECEM COM UMA VOGAL e tenha mais de um "nome"
SELECT * FROM TB_CLIENTE
WHERE CIDADE LIKE '[aeiou]% %A'

-- EMPREGADOS QUE GANHAM R$ 5000 
SELECT * FROM TB_EMPREGADO
WHERE SALARIO = 5000




-- TRABALHANDO COM NULOS NULL

-- EMPREGADOS SEM SALÁRIO (NULL)
SELECT * FROM TB_EMPREGADO
WHERE SALARIO IS NULL

-- EMPREGADOS COM SALARIO
SELECT * FROM TB_EMPREGADO
WHERE SALARIO IS NOT NULL

-- EMPREGADOS QUE NÃO GANHAM r$5000
SELECT * FROM TB_EMPREGADO
WHERE SALARIO != 5000 OR SALARIO IS NULL 


-- FUNÇÃO ISNULL
SELECT 
	NOME, 
	CIDADE, 
	CID_COB, 
	ISNULL(CID_COB,'SEM CIDADE') AS CID_COB_TRATADA, 
	ISNULL(CID_COB, CIDADE) AS CID_COB_TRATADA2,
	COALESCE(CID_COB, CIDADE,'SEM CIDADE') AS CID_COB_TRATADA_COALESCE
	FROM TB_CLIENTE

-- LISTA DE NOME E TELEFONE (SE TIVER FAX, TRAGA O FAX, SENÃO TIVER TRAGA O TELEFONE)
SELECT NOME, FONE1, FAX, ISNULL(FAX,FONE1) AS TELEFONE_TRATADO  
FROM TB_CLIENTE

-- LISTA DE NOME E TELEFONE (SE TIVER FAX, TRAGA O FAX, SENÃO TIVER TRAGA O TELEFONE, SENÃO TIVER NENHUM DOS DOIS RETORNA 'SEM CONTATO')
SELECT NOME, FONE1, FAX, COALESCE(FAX,FONE1,'SEM CONTATO') AS TELEFONE_TRATADO  
FROM TB_CLIENTE

SELECT NOME, FONE1, FAX,  
	COALESCE(FAX,FONE1,'SEM CONTATO') AS TEL_COALESCE,
	ISNULL(FAX,ISNULL(FONE1,'SEM CONTATO')) AS TEL_ISNULL_ANINHADO
FROM TB_CLIENTE