SELECT * FROM TB_VENDEDOR

INSERT INTO TB_VENDEDOR (nome) VALUES ('Vinicius')
INSERT INTO TB_VENDEDOR (nome) VALUES ('Larissa')

SELECT * FROM TB_EMPREGADO

INSERT INTO TB_EMPREGADO (NOME, COD_DEPTO, COD_CARGO) VALUES ('Vinicius Reis', '1', '7')

SELECT * FROM TB_DEPARTAMENTO

SELECT * FROM TB_CARGO

SELECT * FROM TB_PRODUTO

UPDATE TB_PRODUTO SET PRECO_CUSTO = PRECO_CUSTO * 1.15 WHERE COD_TIPO = 2
UPDATE TB_PRODUTO SET PRECO_VENDA = PRECO_VENDA * 1.30 WHERE COD_TIPO = 2