--COLOCANDO O BD EM USO
USE PEDIDOS

-- FUNÇÕES DE AGREGAÇÃO
SELECT 
	AVG(SALARIO)        AS SALARIO_MEDIO,
	COUNT(*)			AS QTD_EMPREGADOS,
	COUNT(COD_DEPTO)    AS QTD_EMPREGADOS_COM_DEPTO,
	COUNT(DISTINCT 
			COD_DEPTO)  AS QTD_DEPTOS_DISTINTOS,
    MIN(SALARIO)		AS MENOR_SALARIO ,
	MAX(SALARIO)		AS MAIOR_SALARIO,
	SUM(SALARIO)		AS SOMA_SALARIOS
FROM TB_EMPREGADO

-- PODE-SE UTILIZAR WHERE
SELECT 
	AVG(SALARIO)        AS SALARIO_MEDIO,
	COUNT(*)			AS QTD_EMPREGADOS,
	COUNT(COD_DEPTO)    AS QTD_EMPREGADOS_COM_DEPTO,
    MIN(SALARIO)		AS MENOR_SALARIO ,
	MAX(SALARIO)		AS MAIOR_SALARIO,
	SUM(SALARIO)		AS SOMA_SALARIOS
FROM TB_EMPREGADO
WHERE COD_DEPTO = 2

-- GROUP BY
SELECT COD_DEPTO, SALARIO 
FROM TB_EMPREGADO ORDER BY COD_DEPTO;

-- TOTAL DE SALÁRIO DE CADA DEPARTAMENTO
SELECT COD_DEPTO, SUM( SALARIO ) AS TOT_SAL, COUNT(*)
FROM TB_EMPREGADO
GROUP BY COD_DEPTO
ORDER BY 2 DESC

-- GROUP BY + JOIN
SELECT V.NOME AS VENDEDOR, COUNT(*) AS QTD_PEDIDOS, C.NOME AS CLIENTE
FROM TB_PEDIDO PE 
JOIN TB_CLIENTE C ON PE.CODCLI = C.CODCLI
JOIN TB_VENDEDOR V ON PE.CODVEN = V.CODVEN
WHERE PE.DATA_EMISSAO BETWEEN '2016.1.1' AND '2016.6.30'
GROUP BY C.NOME, V.NOME
ORDER BY CLIENTE;

-- WHERE (FILTRO)
-- EMPREGADOS QUE GANHAM MAIS DE 5000
SELECT 
	E.COD_DEPTO, 
	D.DEPTO, 
	SUM( E.SALARIO ) AS TOT_SAL
FROM TB_EMPREGADO E
JOIN TB_DEPARTAMENTO D 
ON E.COD_DEPTO = D.COD_DEPTO
WHERE E.SALARIO > 5000
GROUP BY E.COD_DEPTO, D.DEPTO 
ORDER BY TOT_SAL


--HAVING (FILTRO PARA GROUP BY)
-- DEPARTAMENTO QUE GASTAM MAIS DE 5000
SELECT 
	E.COD_DEPTO, 
	D.DEPTO, 
	SUM( E.SALARIO ) AS TOT_SAL
FROM TB_EMPREGADO E
JOIN TB_DEPARTAMENTO D 
ON E.COD_DEPTO = D.COD_DEPTO
GROUP BY E.COD_DEPTO, D.DEPTO 
HAVING SUM(E.SALARIO) > 5000
ORDER BY TOT_SAL

-- Pedidos da vendedora chamada LEIA vendidos para clientes de SP
-- que não compraram em Janeiro de 2017, mas compraram em Dezembro de 2016  
SELECT * FROM TB_PEDIDO
WHERE 
	CODVEN IN (	SELECT CODVEN FROM TB_VENDEDOR	WHERE NOME = 'LEIA' )
	AND
	CODCLI IN (
		SELECT CODCLI FROM TB_CLIENTE
		WHERE ESTADO = 'SP'
		AND CODCLI NOT IN (	SELECT CODCLI FROM TB_PEDIDO
							WHERE DATA_EMISSAO BETWEEN '20170101' AND '20170131')
		AND CODCLI IN (SELECT CODCLI FROM TB_PEDIDO
						WHERE DATA_EMISSAO BETWEEN '20161201' AND '20161231')
)

-- VIEWS
	CREATE VIEW VW_ITENSPEDIDO
	AS
	SELECT I.NUM_PEDIDO, I.NUM_ITEM, I.ID_PRODUTO,
	I.QUANTIDADE, I.PR_UNITARIO, I.DESCONTO,
	I.QUANTIDADE * I.PR_UNITARIO *
	( 1 - I.DESCONTO / 100 ) AS VALOR,
	P.DESCRICAO, T.TIPO, U.UNIDADE, C.COR
	FROM TB_ITENSPEDIDO I 
	JOIN TB_PRODUTO P
	ON I.ID_PRODUTO = P.ID_PRODUTO
	JOIN TB_TIPOPRODUTO T
	ON P.COD_TIPO = T.COD_TIPO
	JOIN TB_UNIDADE U
	ON P.COD_UNIDADE = U.COD_UNIDADE
	JOIN TB_COR C ON I.CODCOR = C.CODCOR
	JOIN TB_PEDIDO PE ON I.NUM_PEDIDO=PE.NUM_PEDIDO;

	SELECT *
	FROM VW_ITENSPEDIDO;

	SELECT NUM_PEDIDO, QUANTIDADE, VALOR, DESCRICAO
	FROM VW_ITENSPEDIDO
	WHERE VALOR > 100;
