-- FUNÇÕES TEXTO
SELECT
	NOME,
	SUBSTRING(NOME, 4, 3)			AS PARTE_DO_NOME,
	LEFT(NOME, 9)					AS COMECO_DO_NOME,
	RIGHT(NOME, 7)					AS FINAL_DO_NOME,
	UPPER('lista de clientes')		AS RELATORIO,
	LOWER(NOME)						AS NOME_MINUSCULO,
	LTRIM(' LISTA DE CLIENTES')		AS RELATORIO_SEM_ESPACO_COMECO, --LISTA DE CLIENTES
	RTRIM('LISTA DE CLIENTES ')		AS RELATORIO_SEM_ESPACO_FINAL, --LISTA DE CLIENTES
	LEN(NOME)						AS QTD_CARACTERES,
	CHARINDEX(' ', NOME)			AS POSICAO_ESPACO,
	RTRIM(SUBSTRING(NOME, 1, 	
			CHARINDEX(' ', NOME))) AS PRIMEIRO_NOME,
	ENDERECO,
	REPLACE(REPLACE(REPLACE(ENDERECO,',',' -Nº '),'R.','RUA '),'AV.','AVENIDA ')	AS ENDERECO_TRATADO,
	REVENDA_CONSUMIDOR,
	CASE REVENDA_CONSUMIDOR	
		WHEN 'C' THEN 'CONSUMIDOR'
		WHEN 'R' THEN 'REVENDA'
		ELSE 'VALIDAR'
	END TIPO_CLIENTE,
	CASE 
		WHEN REVENDA_CONSUMIDOR	 = 'C' THEN 'CONSUMIDOR'
		WHEN REVENDA_CONSUMIDOR	 = 'R' THEN 'REVENDA'
		ELSE 'VALIDAR'
	END TIPO_CLIENTE
FROM TB_CLIENTE

--FUNÇÕES DATA
	SELECT 
		NOME,
		DATA_NASCIMENTO,
		YEAR(DATA_NASCIMENTO)						AS ANO_NASCIMENTO,
		MONTH(DATA_NASCIMENTO)						AS MES_NASCIMENTO,
		DAY(DATA_NASCIMENTO)						AS DIA_NASCIMENTO,
		GETDATE()									AS DATA_SERVIDORBD,
		DATEDIFF(DAY,DATA_NASCIMENTO, GETDATE())	AS QTD_DIAS_VIVIDOS,
		DATEADD(YEAR, 18, DATA_NASCIMENTO)			AS DIA_NIVER_18_ANOS,
		DATEPART(WEEKDAY, DATA_NASCIMENTO)			AS DIA_SEMANA_NASCIMENTO
	FROM TB_EMPREGADO


--FUNÇÕES NUMÉRICAS
	SELECT 
		DESCRICAO,
		PRECO_CUSTO,
		PRECO_VENDA,
		PRECO_CUSTO - PRECO_VENDA,
		ABS(PRECO_CUSTO - PRECO_VENDA)	VALOR_ABSOLUTO,
		CEILING(PRECO_CUSTO)			VALOR_INTEIRO_MAIOR,
		FLOOR(PRECO_CUSTO)				VALOR_INTEIRO_MENOR,
		POWER(PRECO_CUSTO,2)			VALOR_POTENCIA2,
        SQRT(PRECO_CUSTO)				RAIZ_QUADRADA,			
		RAND()							RANDOMICO,
		ROUND(PRECO_CUSTO,2)			ARREDONDAMENTO
	FROM TB_PRODUTO

--FUNÇÕES DE CONVERSÃO
	SELECT
		NOME,
		SALARIO,
		CAST (SALARIO AS INT)  SALARIO_INTEIRO,
		DATA_NASCIMENTO,
		CONVERT( VARCHAR(10), DATA_NASCIMENTO, 103) DATA_NASCIMENTO_TRATADA
	FROM TB_EMPREGADO;