--- Qual comando de insert DECLARATIVO insere um registro 
---na tabela TB_CIDADE com sucesso em um SGBD SQL Server? *
CREATE DATABASE PROVA
GO

USE PROVA
GO


CREATE TABLE TB_ESTADO (
ID_ESTADO INT IDENTITY PRIMARY KEY,
NM_ESTADO VARCHAR(30) NOT NULL
)
DROP TABLE TB_CIDADE
CREATE TABLE TB_CIDADE (
ID_CIDADE INT PRIMARY KEY, 
NM_CIDADE VARCHAR(100) NOT NULL, 
ID_ESTADO INT)

INSERT TB_CIDADE (ID_ESTADO, ID_CIDADE, NM_CIDADE ) VALUES (5, 5, 'Nova cidade')
INSERT INTO TB_CIDADE (ID_ESTADO, ID_CIDADE, NM_CIDADE ) VALUES (0, 5, 'Nova cidade')
INSERT INTO TB_CIDADE (ID_CIDADE, NM_CIDADE) VALUES (3,'teste')
INSERT INTO TB_CIDADE (ID_ESTADO, ID_CIDADE, NM_CIDADE ) VALUES (5, 5, 'Nova cidade')



SELECT * FROM TB_CIDADE
TRUNCATE FROM TB_CIDADE

CREATE TABLE TAB_A (
ID BIGINT IDENTITY PRIMARY KEY,
COL_A CHAR(50) NOT NULL
)


SELECT * FROM TAB_A


CREATE TABLE TB_ALUNO (
NOME_COMPLETO VARCHAR(100),
RA INT
)

INSERT TB_ALUNO VALUES ('Matheus da Silva Santos', 1905184)
SELECT * FROM TB_ALUNO

SELECT LEFT(NOME_COMPLETO,7) FROM TB_ALUNO WHERE RA = 1905184
SELECT LEFT(NOME_COMPLETO,CHARINDEX(' ',NOME_COMPLETO)-1) FROM TB_ALUNO WHERE RA = 1905184
SELECT SUBSTRING(NOME_COMPLETO,1,7) FROM TB_ALUNO WHERE RA = 1905184
SELECT SUBSTRING(NOME_COMPLETO,1,CHARINDEX(' ',NOME_COMPLETO)-1) FROM TB_ALUNO WHERE RA = 1905184


SELECT SUBSTRING(NOME_COMPLETO,1,CHARINDEX(' ',NOME_COMPLETO)-1) FROM TB_ALUNO WHERE RA = 1701731
SELECT LEFT(NOME_COMPLETO,8) FROM TB_ALUNO WHERE RA = 1701731
SELECT LEFT(NOME_COMPLETO,CHARINDEX(' ',NOME_COMPLETO)-1) FROM TB_ALUNO WHERE RA = 1701731
SELECT SUBSTRING(NOME_COMPLETO,1,8) FROM TB_ALUNO WHERE RA = 1701731

TRUNCATE TB_CANIDADATO

Em um banco de dados existem as tabelas 
TB_CIDADE e TB_ESTADO que foram criadas com os respectivos 
comandos 
CREATE TABLE TB_ESTADO 
(ID_ESTADO INT IDENTITY PRIMARY KEY, NM_ESTADO VARCHAR(30) NOT NULL) e
CREATE TABLE TB_CIDADE (ID_CIDADE INT PRIMARY KEY, NM_CIDADE VARCHAR(100) NOT NULL, ID_ESTADO INT NOT NULL);. Qual comando de insert POSICIONAL insere um registro na tabela TB_CIDADE com sucesso em um SGBD SQL Server? * INSERT TB_CIDADE (ID_ESTADO¸ ID_CIDADE¸ NM_CIDADE ) VALUES (0¸5¸'Nova cidade') INSERT TB_CIDADE VALUES ('Nova cidade'¸0) Nenhuma alternativa INSERT TB_CIDADE VALUES (5¸'Nova cidade'¸0) INSERT TB_CIDADE INTO (5¸'Nova cidade'¸0)