-- COLOCANDO O BD EM USO
USE DB_VENDAS;

-- SELECIONAR TODAS AS COLUNAS
SELECT * FROM TB_CLIENTE

-- SELECIONANDO ALGUMAS COLUNAS
SELECT CODCLI, NOME, ICMS FROM TB_CLIENTE

SELECT NOME, SALARIO, SALARIO * 1.1 FROM TB_EMPREGADO

-- UTILIZANDO ALIAS
-- COM A CLAUSULA AS
SELECT
	CODFUN			AS [CÓDIGO DO FUNCIONÁRIO],
	NOME, 
	SALARIO			AS "SALÁRIO ATUAL",
	SALARIO * 1.1	AS 'SALÁRIO PROPOSTO'
FROM TB_EMPREGADO

-- SEM A CLAUSULA AS
SELECT
	CODFUN			CODIGO_FUNCIONARIO,
	NOME, 
	SALARIO			"SALÁRIO ATUAL",
	SALARIO * 1.1	'SALÁRIO PROPOSTO'
FROM TB_EMPREGADO

-- COM IGUAL
SELECT
	[CÓDIGO DO FUNCIONÁRIO] = CODFUN,
	NOME, 
	"SALÁRIO ATUAL" = SALARIO ,
	'SALÁRIO PROPOSTO' = SALARIO * 1.1	
FROM TB_EMPREGADO

-- APELIDANDO TABELAS
SELECT * FROM TB_EMPREGADO EMP

-- OPERADORES MATEMÁTICOS
SELECT 
	NOME, SALARIO, PREMIO_MENSAL,
	SALARIO + PREMIO_MENSAL			SALARIO_BONIFICADO,
	SALARIO * 12					SALARIO_ANUAL,
	SALARIO + PREMIO_MENSAL * 12	SALARIO_BONIFICADO_ATUAL_ERRO_PRIORIZACAO,
	(SALARIO + PREMIO_MENSAL) * 12	SALARIO_BONIFICADO_ATUAL
FROM TB_EMPREGADO

-- TODOS OS SALARIOS
SELECT SALARIO FROM TB_EMPREGADO

-- SOMENTE OS SALARIOS "DIFERENTES" DISTINTOS
SELECT DISTINCT SALARIO FROM TB_EMPREGADO

SELECT DISTINCT COD_DEPTO, SALARIO FROM TB_EMPREGADO

-- QUAIS ESTADOS EU POSSUO CLIENTES
SELECT DISTINCT ESTADO FROM TB_CLIENTE

-- EMPREGADOS ORDENADOS POR QUEM GANHA MENOS
SELECT * FROM TB_EMPREGADO
ORDER BY SALARIO ASC -- ORDEM CRESCENTE, O USO DO PARAMETRO ASC É OPCIONAL

SELECT NOME FROM TB_EMPREGADO
ORDER BY SALARIO -- ORDEM CRESCENTE, O USO DO PARAMETRO ASC É OPCIONAL

-- EMPREGADOS ORDENADOS POR QUEM GANHA MAIS
SELECT * FROM TB_EMPREGADO
ORDER BY SALARIO DESC -- ORDEM DECRESCENTE, O USO DO PARAMETRO DESC É OBRIGATÓRIO 

SELECT NOME FROM TB_EMPREGADO
ORDER BY SALARIO -- ORDEM CRESCENTE, O USO DO PARAMETRO ASC É OPCIONAL

-- ORDENANDO PELA POSIÇÃO DA COLUNA NO SELECT 
SELECT NOME, SALARIO FROM TB_EMPREGADO
ORDER BY 1 -- ORDENANDO CRESCENTEMENTE PELO NOME

SELECT NOME, SALARIO FROM TB_EMPREGADO
ORDER BY 2 DESC-- ORDENANDO DECRESCENTEMENTE PELO SALARIO 
FROM TB_EMPREGADO ORDER BY DATA_ADMISSAO DESC

-- LISTAR O EMPREGADO QUE GANHA MAIS
SELECT TOP 1 WITH TIES * FROM TB_EMPREGADO 
ORDER BY SALARIO DESC

-- EXIBIR 10% DOS PEDIDOS
SELECT TOP 10 PERCENT * FROM TB_PEDIDO

-- EXIBIR 1% DOS PEDIDOS DE FORMA ALEATÓRIA
SELECT TOP 1 PERCENT * FROM TB_PEDIDO
ORDER BY NEWID()