-- EXCLUINDO UMA TABELA
DROP TABLE IF EXISTS ALUNOS;

-- CRIANDO TABELA ALUNOS
	CREATE TABLE ALUNOS
	(
		NUM_ALUNO INT IDENTITY , 
		NOME VARCHAR(30) NOT NULL,
		DATA_NASCIMENTO DATETIME,
		IDADE TINYINT,
		E_MAIL VARCHAR(50),
		FONE_RES CHAR(8),
		FONE_COM CHAR(8),
		FAX CHAR(8),
		CELULAR CHAR(9),
		PROFISSAO VARCHAR(40),
		EMPRESA VARCHAR(50) 
	);

-- INSERINDO UM UNICO REGISTRO
INSERT INTO ALUNOS (NOME, DATA_NASCIMENTO, IDADE, E_MAIL, FONE_RES, FONE_COM, FAX, CELULAR, PROFISSAO, EMPRESA)
VALUES ('Gustavo Ferreira', '19870427', 33, 'gustavo@gferreira.com','20939393','', '', '992341254','PROFESSOR','FIT');

-- EXIBINDO 
SELECT * FROM ALUNOS

-- INSERINDO MAIS DE UM REGISTRO EM UM UNICO INSERT
INSERT INTO ALUNOS (NOME, DATA_NASCIMENTO)
VALUES
('Luizinho'  ,'2005/6/5'),
('Mariazinha','2010-5-8'),
('Suely'     ,'1952.7.14'),
('Flavia'    ,'19740612')

-- erro pq não colocamos o nome que é obrigatório (NOT NULL)
INSERT ALUNOS (PROFISSAO) VALUES ('ESTUDANTE')


-- INSERT DECLARATIVO (INFORMO AS COLUNAS)
INSERT INTO ALUNOS -- INTO NO SQL SERVER É OPCIONAL
(NOME, IDADE)
VALUES
('RONY',25)

INSERT ALUNOS -- INTO NO SQL SERVER É OPCIONAL
(NOME, IDADE)
VALUES
('GABRIEL',19), ('MARCOS',42)

-- INSERT POSICIONAL
INSERT INTO ALUNOS -- INTO NO SQL SERVER É OPCIONAL
VALUES
('André','1990-01-01',31,'andre@fit.com','23456789','33330000','','999998888','DBA','IMPACTA TECNOLOGIA'),
('Matheus','2000-02-01',21,'math@fit.com','22223333','33330001','','988887777','DESENVOLVEDOR','IMPACTA TECNOLOGIA')

--CRIANDO TABELA 
CREATE TABLE ALUNOS2
( NUM_ALUNO INT,	NOME VARCHAR(30),	DATA_NASCIMENTO DATETIME,	IDADE TINYINT,
E_MAIL VARCHAR(50),	FONE_RES CHAR(8),	FONE_COM CHAR(8),	FAX CHAR(8), CELULAR CHAR(9),
PROFISSAO VARCHAR(40), EMPRESA VARCHAR(50) );

SELECT * FROM ALUNOS2

-- INSERINDO COM SELECT
INSERT INTO ALUNOS2
SELECT * FROM ALUNOS

-- SELECT COM INSERT
SELECT * 
INTO ALUNOS3
FROM ALUNOS

SELECT * FROM ALUNOS3

-- SELECT COM INSERT
SELECT TOP 0 * 
INTO ALUNOS4
FROM ALUNOS

--
SELECT * FROM TB_EMPREGADO

-- AUMENTANDO 20% DO SALÁRIO (UNICA COLUNA)
UPDATE TB_EMPREGADO
SET SALARIO = SALARIO * 1.2  -- SALARIO = SALARIO + (SALARIO * 0.2)

-- ALTERANDO O ENDERECO ( MAIS DE UMA COLUNA) DO CLIENTE CODIGO 5
UPDATE TB_CLIENTE
SET ENDERECO = 'AV PAULISTA, 1009',
	BAIRRO	=	'CERQUEIRA CESAR',
	CIDADE	=	'SAO PAULO'	
WHERE CODCLI = 5

UPDATE TB_CLIENTE
SET ENDERECO = 'AV PAULISTA, 1009',
	BAIRRO	=	'CERQUEIRA CESAR',
	CIDADE	=	'SAO PAULO'	
WHERE NOME = 'AVEL APOLIMARIO VEICULOS S.A'

-- ALTERAR EMAIL PARA NULO DOS CLIENTES DE SP OU RJ
UPDATE TB_CLIENTE
SET E_MAIL = NULL
WHERE ESTADO = 'SP' OR ESTADO = 'RJ'

-- ALTERAR EMAIL PARA NULO DOS CLIENTES DE MG COM ICMS MAIOR QUE 0
UPDATE TB_CLIENTE
SET E_MAIL = NULL
WHERE ESTADO = 'MG' AND ICMS > 0

-- CRIAR COPIA DE UMA TABELA
SELECT * 
INTO EMPREGADOS_TMP 
select * FROM TB_EMPREGADO

-- EXCLUINDO ALGUNS REGISTROS 
-- EMPREGADOS COM SALARIO MAIOR QUE 5000
DELETE FROM EMPREGADOS_TMP -- NO SQL SERVER O FROM É OPCIONAL
WHERE SALARIO > 5000

-- EXCLUIR OS EMPREGADOS DE CODIGO 3,5,7
DELETE FROM EMPREGADOS_TMP 
WHERE CODFUN = 3 or CODFUN = 5 or CODFUN = 7 -- CODFUN IN (3,5,7)


-- EXCLUIR TODOS OS REGISTROS
DELETE FROM EMPREGADOS_TMP --DML - ATUA NA MANIPULAÇÃO DOS DADOS
--OU
TRUNCATE TABLE EMPREGADOS_TMP --DDL - ATUA NA ESTRUTURA DOS DADOS 