-- 1
USE PEDIDOS

-- 2
SELECT TB_PEDIDO.NUM_PEDIDO, TB_PEDIDO.DATA_EMISSAO, TB_PEDIDO.VLR_TOTAL, TB_VENDEDOR.NOME [NOME DO VENDEDOR]
FROM TB_PEDIDO 
INNER JOIN TB_VENDEDOR ON TB_PEDIDO.CODVEN = TB_VENDEDOR.CODVEN;

-- 3
SELECT TB_PEDIDO.NUM_PEDIDO, TB_PEDIDO.DATA_EMISSAO, TB_PEDIDO.VLR_TOTAL, TB_CLIENTE.NOME [NOME DO CLIENTE]
FROM TB_PEDIDO 
INNER JOIN TB_CLIENTE ON TB_PEDIDO.CODCLI = TB_CLIENTE.CODCLI;

-- 4
SELECT TB_PEDIDO.*, TB_VENDEDOR.NOME [NOME DO VENDEDOR], TB_CLIENTE.NOME [NOME DO CLIENTE]
FROM TB_PEDIDO 
JOIN TB_VENDEDOR ON TB_PEDIDO.CODVEN = TB_VENDEDOR.CODVEN
JOIN TB_CLIENTE ON TB_PEDIDO.CODCLI = TB_CLIENTE.CODCLI;

-- 5
SELECT TB_ITENSPEDIDO.*, TB_PRODUTO.DESCRICAO FROM TB_ITENSPEDIDO 
	JOIN TB_PRODUTO ON TB_ITENSPEDIDO.ID_PRODUTO = TB_PRODUTO.ID_PRODUTO;

-- 6
SELECT TB_PRODUTO.COD_PRODUTO, TB_PRODUTO.DESCRICAO, TB_TIPOPRODUTO.TIPO 
FROM TB_PRODUTO
	JOIN TB_TIPOPRODUTO ON TB_TIPOPRODUTO.COD_TIPO = TB_PRODUTO.COD_TIPO;

-- 7
SELECT TB_PRODUTO.COD_PRODUTO, TB_PRODUTO.DESCRICAO, TB_TIPOPRODUTO.TIPO, TB_UNIDADE.UNIDADE 
FROM TB_PRODUTO
	JOIN TB_TIPOPRODUTO ON TB_TIPOPRODUTO.COD_TIPO = TB_PRODUTO.COD_TIPO
	JOIN TB_UNIDADE ON TB_UNIDADE.COD_UNIDADE = TB_PRODUTO.COD_UNIDADE;

-- 8
SELECT TB_ITENSPEDIDO.NUM_PEDIDO, TB_ITENSPEDIDO.NUM_ITEM, TB_ITENSPEDIDO.COD_PRODUTO, TB_ITENSPEDIDO.QUANTIDADE,
	   TB_ITENSPEDIDO.PR_UNITARIO, TB_PRODUTO.COD_PRODUTO, TB_PRODUTO.DESCRICAO, TB_TIPOPRODUTO.TIPO, TB_UNIDADE.UNIDADE
FROM TB_ITENSPEDIDO 
	JOIN TB_PRODUTO ON TB_ITENSPEDIDO.ID_PRODUTO = TB_PRODUTO.ID_PRODUTO
	JOIN TB_TIPOPRODUTO ON TB_PRODUTO.COD_TIPO = TB_TIPOPRODUTO.COD_TIPO
	JOIN TB_UNIDADE ON TB_PRODUTO.COD_UNIDADE = TB_UNIDADE.COD_UNIDADE;


SELECT TB_ITENSPEDIDO.NUM_PEDIDO, TB_ITENSPEDIDO.NUM_ITEM, TB_ITENSPEDIDO.COD_PRODUTO, TB_ITENSPEDIDO.QUANTIDADE,
	   TB_ITENSPEDIDO.PR_UNITARIO, TB_PRODUTO.COD_PRODUTO, TB_PRODUTO.DESCRICAO, TB_TIPOPRODUTO.TIPO, TB_UNIDADE.UNIDADE
FROM TB_TIPOPRODUTO 
	JOIN TB_PRODUTO ON TB_PRODUTO.COD_TIPO = TB_TIPOPRODUTO.COD_TIPO
	JOIN TB_UNIDADE ON TB_PRODUTO.COD_UNIDADE = TB_UNIDADE.COD_UNIDADE
	JOIN TB_ITENSPEDIDO ON TB_ITENSPEDIDO.ID_PRODUTO = TB_PRODUTO.ID_PRODUTO;

/*TB_ITENSPEDIDO 
	JOIN TB_PRODUTO ON TB_ITENSPEDIDO.ID_PRODUTO = TB_PRODUTO.ID_PRODUTO
	JOIN TB_TIPOPRODUTO ON TB_PRODUTO.COD_TIPO = TB_TIPOPRODUTO.COD_TIPO
	JOIN TB_UNIDADE ON TB_PRODUTO.COD_UNIDADE = TB_UNIDADE.COD_UNIDADE;
*/
-- 9
SELECT TB_ITENSPEDIDO.NUM_PEDIDO, TB_ITENSPEDIDO.NUM_ITEM, TB_ITENSPEDIDO.COD_PRODUTO, TB_ITENSPEDIDO.QUANTIDADE,
	   TB_ITENSPEDIDO.PR_UNITARIO, TB_PRODUTO.COD_PRODUTO, TB_PRODUTO.DESCRICAO, TB_TIPOPRODUTO.TIPO, TB_UNIDADE.UNIDADE,
	   TB_COR.COR
FROM TB_ITENSPEDIDO 
	JOIN TB_PRODUTO ON TB_ITENSPEDIDO.ID_PRODUTO = TB_PRODUTO.ID_PRODUTO
	JOIN TB_TIPOPRODUTO ON TB_PRODUTO.COD_TIPO = TB_TIPOPRODUTO.COD_TIPO
	JOIN TB_UNIDADE ON TB_PRODUTO.COD_UNIDADE = TB_UNIDADE.COD_UNIDADE
	JOIN TB_COR ON TB_COR.CODCOR = TB_ITENSPEDIDO.CODCOR;

-- 10
SELECT TB_PEDIDO.*--, TB_VENDEDOR.NOME [NOME DO VENDEDOR] 
FROM TB_PEDIDO JOIN TB_VENDEDOR ON TB_PEDIDO.CODVEN = TB_VENDEDOR.CODVEN
WHERE NOME = 'MARCELO' AND DATA_EMISSAO BETWEEN '2017.1.1' AND '2017.1.31';

-- 11 
SELECT TB_CLIENTE.NOME, TB_PEDIDO.DATA_EMISSAO 
FROM TB_CLIENTE JOIN TB_PEDIDO ON TB_PEDIDO.CODCLI = TB_CLIENTE.CODCLI 
WHERE TB_PEDIDO.DATA_EMISSAO BETWEEN '2017.1.1' AND '2017.1.31' ;

SELECT DISTINCT TB_CLIENTE.NOME
FROM TB_CLIENTE JOIN TB_PEDIDO ON TB_PEDIDO.CODCLI = TB_CLIENTE.CODCLI 
WHERE TB_PEDIDO.DATA_EMISSAO BETWEEN '2017.1.1' AND '2017.1.31' ;

-- 12
SELECT TB_PRODUTO.DESCRICAO, TB_PEDIDO.DATA_EMISSAO 
FROM TB_PRODUTO 
JOIN  TB_ITENSPEDIDO ON TB_PRODUTO.ID_PRODUTO = TB_ITENSPEDIDO.ID_PRODUTO 
JOIN TB_PEDIDO ON TB_ITENSPEDIDO.NUM_PEDIDO = TB_PEDIDO.NUM_PEDIDO
WHERE TB_PEDIDO.DATA_EMISSAO BETWEEN '2017.1.1' AND '2017.1.31';

-- 13
SELECT TB_PEDIDO.NUM_PEDIDO, TB_PEDIDO.VLR_TOTAL, TB_CLIENTE.NOME FROM TB_PEDIDO
JOIN TB_CLIENTE ON TB_CLIENTE.CODCLI = TB_PEDIDO.CODCLI
WHERE TB_CLIENTE.NOME LIKE 'MARCIO%' AND TB_PEDIDO.DATA_EMISSAO BETWEEN '2017.1.1' AND '2017.1.31';

-- 14
SELECT TB_ITENSPEDIDO.NUM_PEDIDO, TB_ITENSPEDIDO.QUANTIDADE, TB_ITENSPEDIDO.PR_UNITARIO,
 TB_PRODUTO.DESCRICAO, TB_VENDEDOR.NOME
FROM TB_ITENSPEDIDO JOIN TB_PRODUTO ON TB_ITENSPEDIDO.ID_PRODUTO = TB_PRODUTO.ID_PRODUTO
					JOIN TB_PEDIDO ON TB_PRODUTO.ID_PRODUTO = TB_PRODUTO.ID_PRODUTO
					JOIN TB_VENDEDOR ON TB_PEDIDO.CODVEN = TB_VENDEDOR.CODVEN ;

-- 15
SELECT TB_PEDIDO.*, TB_ITENSPEDIDO.DESCONTO, TB_PRODUTO.DESCRICAO, TB_CLIENTE.NOME [NOME CLIENTE], 
TB_VENDEDOR.NOME [NOME VENDEDOR], TB_ITENSPEDIDO.QUANTIDADE 
FROM TB_PEDIDO 
	JOIN TB_ITENSPEDIDO ON TB_PEDIDO.NUM_PEDIDO = TB_ITENSPEDIDO.NUM_PEDIDO
	JOIN TB_PRODUTO ON TB_ITENSPEDIDO.ID_PRODUTO = TB_PRODUTO.ID_PRODUTO
	JOIN TB_CLIENTE ON TB_PEDIDO.CODCLI = TB_CLIENTE.CODCLI
    JOIN TB_VENDEDOR ON TB_PEDIDO.CODVEN = TB_VENDEDOR.CODVEN
WHERE DESCONTO > 7 

--16
SELECT
   I.NUM_PEDIDO, I.NUM_ITEM, I.COD_PRODUTO, PR.DESCRICAO,
   I.QUANTIDADE, I.PR_UNITARIO, T.TIPO, U.UNIDADE, CR.COR,
   PE.DATA_EMISSAO
FROM TB_ITENSPEDIDO I
   JOIN TB_PRODUTO PR ON I.ID_PRODUTO = PR.ID_PRODUTO
   JOIN TB_COR CR ON I.CODCOR = CR.CODCOR
   JOIN TB_TIPOPRODUTO T ON PR.COD_TIPO = T.COD_TIPO
   JOIN TB_UNIDADE U ON PR.COD_UNIDADE = U.COD_UNIDADE
   JOIN TB_PEDIDO PE ON I.NUM_PEDIDO = PE.NUM_PEDIDO     
WHERE PE.DATA_EMISSAO BETWEEN '2017.1.1' AND '2017.1.31' AND COR = 'LARANJA'

-- 17
SELECT F.NOME,F.FONE1 FROM TB_FORNECEDOR F
JOIN TB_PROD_FORN P  ON F.COD_FORNECEDOR = P.COD_FORNECEDOR 
JOIN TB_PRODUTO S ON S.ID_PRODUTO = P.ID_PRODUTO
WHERE S.ID_PRODUTO = 7 ;

-- 18
SELECT DESCRICAO  FROM TB_PRODUTO P
JOIN TB_PROD_FORN PF  ON P.ID_PRODUTO = PF.ID_PRODUTO 
JOIN TB_FORNECEDOR F  ON PF.COD_FORNECEDOR = F.COD_FORNECEDOR
WHERE F.NOME LIKE 'LINCE%'

--19
SELECT NOME, FONE1, DESCRICAO  FROM TB_PRODUTO P
JOIN TB_PROD_FORN PF  ON P.ID_PRODUTO = PF.ID_PRODUTO 
JOIN TB_FORNECEDOR F  ON PF.COD_FORNECEDOR = F.COD_FORNECEDOR
WHERE QTD_REAL < QTD_MINIMA

--20
SELECT DESCRICAO  FROM TB_PRODUTO P
JOIN TB_PROD_FORN PF  ON P.ID_PRODUTO = PF.ID_PRODUTO 
JOIN TB_FORNECEDOR F  ON PF.COD_FORNECEDOR = F.COD_FORNECEDOR
WHERE F.NOME LIKE 'FESTO%'


-- 21. Liste os clientes que não realizaram nenhuma compra.
SELECT NOME 
FROM TB_CLIENTE
 LEFT JOIN TB_PEDIDO
 ON TB_CLIENTE.CODCLI = TB_PEDIDO.CODCLI
 WHERE TB_PEDIDO.CODCLI IS NULL

SELECT NOME 
FROM TB_PEDIDO
 RIGHT JOIN TB_CLIENTE
 ON TB_CLIENTE.CODCLI = TB_PEDIDO.CODCLI
 WHERE TB_PEDIDO.CODCLI IS NULL
 
-- 22. Liste os clientes que não realizaram nenhuma compra em Jan/2016
SELECT NOME
	FROM TB_CLIENTE
		LEFT JOIN TB_PEDIDO
		ON TB_CLIENTE.CODCLI = TB_PEDIDO.CODCLI AND YEAR(DATA_EMISSAO) = 2016 AND MONTH(DATA_EMISSAO) = 1
WHERE TB_PEDIDO.CODCLI IS NULL

-- 23. Liste os Produtos que nunca foram vendidos.
SELECT 
	DESCRICAO, *
FROM TB_PRODUTO	
	LEFT JOIN TB_ITENSPEDIDO 
	ON TB_PRODUTO.ID_PRODUTO = TB_ITENSPEDIDO.ID_PRODUTO
WHERE TB_ITENSPEDIDO.ID_PRODUTO IS NULL

-- 24. Liste os clientes que compraram com a vendedora LEIA.
SELECT
	DISTINCT TB_CLIENTE.NOME
FROM TB_CLIENTE	
	INNER JOIN TB_PEDIDO ON TB_CLIENTE.CODCLI = TB_PEDIDO.CODCLI
	INNER JOIN TB_VENDEDOR ON TB_VENDEDOR.CODVEN = TB_PEDIDO.CODVEN
WHERE TB_VENDEDOR.NOME = 'LEIA'

-- 25. Liste os clientes que nunca compraram com a vendedora LEIA.
SELECT DISTINCT TB_CLIENTE.NOME
FROM TB_PEDIDO 
	INNER JOIN TB_VENDEDOR ON TB_VENDEDOR.CODVEN = TB_PEDIDO.CODVEN AND TB_VENDEDOR.NOME = 'LEIA'
	RIGHT JOIN  TB_CLIENTE ON TB_CLIENTE.CODCLI = TB_PEDIDO.CODCLI	
WHERE TB_VENDEDOR.CODVEN IS NULL
