-- 1. Coloque em uso o banco de dados DB_VENDAS;
USE DB_VENDAS

-- 2. Liste os campos NUM_PEDIDO, DATA_EMISSAO e VLR_TOTAL de PEDIDOS, seguidos de NOME do vendedor;
SELECT 
	NUM_PEDIDO,
	DATA_EMISSAO,
	VLR_TOTAL,
	NOME
FROM TB_PEDIDO
	INNER JOIN -- PODERIA SER APENAS JOIN
	TB_VENDEDOR 
	ON TB_PEDIDO.CODVEN = TB_VENDEDOR.CODVEN

-- 4. Liste os pedidos com o nome do vendedor e o nome do cliente;
SELECT
	TB_PEDIDO.*,
	TB_VENDEDOR.NOME AS VENDEDOR,
	TB_CLIENTE.NOME AS CLIENTE
FROM TB_CLIENTE
	INNER JOIN TB_PEDIDO ON TB_CLIENTE.CODCLI = TB_PEDIDO.CODCLI
	INNER JOIN TB_VENDEDOR ON TB_VENDEDOR.CODVEN = TB_PEDIDO.CODVEN

-- 9. Liste os campos NUM_PEDIDO, NUM_ITEM, COD_PRODUTO, QUANTIDADE e PR_UNITARIO da tabela ITENSPEDIDO, e os campos COD_PRODUTO e DESCRICAO da tabela PRODUTOS, seguidos da descrição do tipo de produto, do nome da unidade de medida e do nome da cor;
SELECT
	IP.NUM_PEDIDO,
	IP.NUM_ITEM,
	IP.COD_PRODUTO,
	IP.QUANTIDADE,
	IP.PR_UNITARIO,
	PR.COD_PRODUTO,
	PR.DESCRICAO,
	TP.TIPO,
	UN.UNIDADE,
	CR.COR
FROM TB_ITENSPEDIDO IP
	INNER JOIN TB_PRODUTO PR ON IP.ID_PRODUTO = PR.ID_PRODUTO 
	INNER JOIN TB_TIPOPRODUTO TP ON PR.COD_TIPO = TP.COD_TIPO
	INNER JOIN TB_UNIDADE UN ON UN.COD_UNIDADE = PR.COD_UNIDADE
	INNER JOIN TB_COR CR ON CR.CODCOR = IP.CODCOR

-- 11. Liste os nomes dos clientes que efetuaram compras em janeiro de 2017;
SELECT DISTINCT NOME
FROM TB_CLIENTE	
	INNER JOIN TB_PEDIDO 
	ON TB_PEDIDO.CODCLI = TB_CLIENTE.CODCLI
WHERE DATA_EMISSAO BETWEEN '20170101' AND '20170131'
-- YEAR(DATA_EMISSAO) = 2017 AND MONTH(DATA_EMISSAO) = 1
ORDER BY NOME

-- 17. Liste NOME e FONE1 dos fornecedores que venderam o produto CANETA STAR I;
SELECT 
	NOME, 
	FONE1
FROM TB_FORNECEDOR
	INNER JOIN TB_PROD_FORN ON TB_FORNECEDOR.COD_FORNECEDOR = TB_PROD_FORN.COD_FORNECEDOR
	INNER JOIN TB_PRODUTO ON TB_PRODUTO.ID_PRODUTO = TB_PROD_FORN.ID_PRODUTO
WHERE DESCRICAO = 'CANETA STAR I'

-- 21. Liste os clientes que não realizaram nenhuma compra.
SELECT NOME 
FROM TB_CLIENTE
 LEFT JOIN TB_PEDIDO
 ON TB_CLIENTE.CODCLI = TB_PEDIDO.CODCLI
 WHERE TB_PEDIDO.CODCLI IS NULL

SELECT NOME 
FROM TB_PEDIDO
 RIGHT JOIN TB_CLIENTE
 ON TB_CLIENTE.CODCLI = TB_PEDIDO.CODCLI
 WHERE TB_PEDIDO.CODCLI IS NULL
 
-- 22. Liste os clientes que não realizaram nenhuma compra em Jan/2016
SELECT NOME
	FROM TB_CLIENTE
		LEFT JOIN TB_PEDIDO
		ON TB_CLIENTE.CODCLI = TB_PEDIDO.CODCLI AND YEAR(DATA_EMISSAO) = 2016 AND MONTH(DATA_EMISSAO) = 1
WHERE TB_PEDIDO.CODCLI IS NULL

-- 23. Liste os Produtos que nunca foram vendidos.
SELECT 
	DESCRICAO, *
FROM TB_PRODUTO	
	LEFT JOIN TB_ITENSPEDIDO 
	ON TB_PRODUTO.ID_PRODUTO = TB_ITENSPEDIDO.ID_PRODUTO
WHERE TB_ITENSPEDIDO.ID_PRODUTO IS NULL

-- 24. Liste os clientes que compraram com a vendedora LEIA.
SELECT
	DISTINCT TB_CLIENTE.NOME
FROM TB_CLIENTE	
	INNER JOIN TB_PEDIDO ON TB_CLIENTE.CODCLI = TB_PEDIDO.CODCLI
	INNER JOIN TB_VENDEDOR ON TB_VENDEDOR.CODVEN = TB_PEDIDO.CODVEN
WHERE TB_VENDEDOR.NOME = 'LEIA'

-- 25. Liste os clientes que nunca compraram com a vendedora LEIA.
SELECT DISTINCT TB_CLIENTE.NOME
FROM TB_PEDIDO 
	INNER JOIN TB_VENDEDOR ON TB_VENDEDOR.CODVEN = TB_PEDIDO.CODVEN AND TB_VENDEDOR.NOME = 'LEIA'
	RIGHT JOIN  TB_CLIENTE ON TB_CLIENTE.CODCLI = TB_PEDIDO.CODCLI	
WHERE TB_VENDEDOR.CODVEN IS NULL
