CREATE DATABASE AC05

USE AC05

CREATE TABLE TB_DEPARTAMENTO(
COD_DEPTO INT IDENTITY,
NOME VARCHAR(255) NOT NULL,

CONSTRAINT PK_COD_DEPTO PRIMARY KEY (COD_DEPTO)
)

CREATE TABLE TB_SECAO (
COD_SECAO INT IDENTITY,
NOME VARCHAR(255) NOT NULL,
COD_DEPTO INT NOT NULL,

CONSTRAINT PK_SECAO PRIMARY KEY (COD_SECAO),
CONSTRAINT FK_COD_DEPTO FOREIGN KEY (COD_DEPTO) REFERENCES TB_DEPARTAMENTO (COD_DEPTO)
)

INSERT INTO TB_DEPARTAMENTO VALUES ('AUTOMOTIVO'), ('ARTIGO DE FESTAS'), ('BEBES');

INSERT INTO TB_SECAO VALUES ('PNEUS NOVOS', 1), ('SOM AUTOMOTIVO', 1), ('GPS', 1);

INSERT INTO TB_SECAO VALUES ( 'ALARMES', 1)

SELECT * FROM TB_SECAO


CREATE TABLE TB_CLIENTE (
ID_CLI INT PRIMARY KEY IDENTITY, 
CPF_CLI CHAR(11), 
EMAIL_CLI VARCHAR(100) NOT NULL, 
SENHA_CLI VARCHAR(10) NOT NULL, 
DT_NASC_CLI DATE);

ALTER TABLE TB_CLIENTE ALTER COLUMN DT_NASC_CLI DATE NOT NULL;

SELECT * FROM TB_CLIENTE

INSERT INTO TB_CLIENTE (CPF_CLI, EMAIL_CLI,SENHA_CLI) VALUES ('12234567898', 'teste@teste', '1234567')