-- FUNÇÕES DE AGREGAÇÃO
SELECT 
	SUM(SALARIO)					AS TOTAL_SALARIO,				-- SOMA
	COUNT(*)						AS QTD_EMPREGADOS,				-- CONTAGEM DE REGISTROS
	COUNT(SALARIO)					AS QTD_EMPREGADOS_ASSALARIADOS, -- CONTAGEM DE VALORES NÃO NULOS
	COUNT(DISTINCT SALARIO)			AS QTD_UNICAS_SALARIO,			-- CONTAGEM DE VALORES DIFERENTES
	MAX(PREMIO_MENSAL)				AS MAIOR_PREMIO,				-- MAIOR VALOR DA COLUNA
	MIN(PREMIO_MENSAL)				AS MENOR_PREMIO,				-- MENOR VALOR DA COLUNA
	SUM(PREMIO_MENSAL)				AS SOMA_PREMIO,					-- SOMA
	AVG(PREMIO_MENSAL)				AS PREMIO_MEDIO,				-- MÉDIA ARITIMÉTICA
	AVG(ISNULL(PREMIO_MENSAL,0))	AS PREMIO_MEDIO_TRATADO
FROM TB_EMPREGADO

-- FUNÇÕES DE AGREGAÇÃO
SELECT 
	SUM(SALARIO)					AS TOTAL_SALARIO,				-- SOMA
	COUNT(*)						AS QTD_EMPREGADOS,				-- CONTAGEM DE REGISTROS
	COUNT(SALARIO)					AS QTD_EMPREGADOS_ASSALARIADOS, -- CONTAGEM DE VALORES NÃO NULOS
	COUNT(DISTINCT SALARIO)			AS QTD_UNICAS_SALARIO,			-- CONTAGEM DE VALORES DIFERENTES
	MAX(PREMIO_MENSAL)				AS MAIOR_PREMIO,				-- MAIOR VALOR DA COLUNA
	MIN(PREMIO_MENSAL)				AS MENOR_PREMIO,				-- MENOR VALOR DA COLUNA
	SUM(PREMIO_MENSAL)				AS SOMA_PREMIO,					-- SOMA
	AVG(PREMIO_MENSAL)				AS PREMIO_MEDIO,				-- MÉDIA ARITIMÉTICA
	AVG(ISNULL(PREMIO_MENSAL,0))	AS PREMIO_MEDIO_TRATADO
FROM TB_EMPREGADO
WHERE COD_DEPTO = 4

-- FUNÇÕES DE AGREGAÇÃO
SELECT 
	SUM(SALARIO)					AS TOTAL_SALARIO,				-- SOMA
	COUNT(*)						AS QTD_EMPREGADOS,				-- CONTAGEM DE REGISTROS
	COUNT(SALARIO)					AS QTD_EMPREGADOS_ASSALARIADOS, -- CONTAGEM DE VALORES NÃO NULOS
	COUNT(DISTINCT SALARIO)			AS QTD_UNICAS_SALARIO,			-- CONTAGEM DE VALORES DIFERENTES
	MAX(PREMIO_MENSAL)				AS MAIOR_PREMIO,				-- MAIOR VALOR DA COLUNA
	MIN(PREMIO_MENSAL)				AS MENOR_PREMIO,				-- MENOR VALOR DA COLUNA
	SUM(PREMIO_MENSAL)				AS SOMA_PREMIO,					-- SOMA
	AVG(PREMIO_MENSAL)				AS PREMIO_MEDIO,				-- MÉDIA ARITIMÉTICA
	AVG(ISNULL(PREMIO_MENSAL,0))	AS PREMIO_MEDIO_TRATADO
FROM TB_EMPREGADO JOIN 
	TB_DEPARTAMENTO ON TB_EMPREGADO.COD_DEPTO = TB_DEPARTAMENTO.COD_DEPTO
WHERE DEPTO = 'RH'

-- FUNÇÕES DE AGREGAÇÃO
SELECT 
	SUM(SALARIO)					AS TOTAL_SALARIO,				-- SOMA
	COUNT(*)						AS QTD_EMPREGADOS,				-- CONTAGEM DE REGISTROS
	COUNT(SALARIO)					AS QTD_EMPREGADOS_ASSALARIADOS, -- CONTAGEM DE VALORES NÃO NULOS
	COUNT(DISTINCT SALARIO)			AS QTD_UNICAS_SALARIO,			-- CONTAGEM DE VALORES DIFERENTES
	MAX(PREMIO_MENSAL)				AS MAIOR_PREMIO,				-- MAIOR VALOR DA COLUNA
	MIN(PREMIO_MENSAL)				AS MENOR_PREMIO,				-- MENOR VALOR DA COLUNA
	SUM(PREMIO_MENSAL)				AS SOMA_PREMIO,					-- SOMA
	AVG(PREMIO_MENSAL)				AS PREMIO_MEDIO,				-- MÉDIA ARITIMÉTICA
	AVG(ISNULL(PREMIO_MENSAL,0))	AS PREMIO_MEDIO_TRATADO
FROM TB_EMPREGADO JOIN 
	TB_DEPARTAMENTO ON TB_EMPREGADO.COD_DEPTO = TB_DEPARTAMENTO.COD_DEPTO
WHERE DEPTO = 'PESSOAL'

-- TEMPO MEDIO DE ENTREGA DOS ITENS
SELECT 
	AVG(DATEDIFF(day, DATA_EMISSAO, DATA_ENTREGA))
FROM TB_PEDIDO
	INNER JOIN TB_ITENSPEDIDO ON TB_PEDIDO.NUM_PEDIDO = TB_ITENSPEDIDO.NUM_PEDIDO

-- QUANTIDADE DE EMPREGADOS, VALOR TOTAL DE SALARIO, MEDIA DOS SALÁRIOS POR DEPARTAMENTO 
SELECT 
	DEPTO, 
	COUNT(*)		AS QTD_EMPREGADOS,
	SUM(SALARIO)	AS TOT_SALARIO,
	AVG(SALARIO)	AS MED_SALARIO
FROM TB_EMPREGADO JOIN 
	TB_DEPARTAMENTO ON TB_EMPREGADO.COD_DEPTO = TB_DEPARTAMENTO.COD_DEPTO
GROUP BY DEPTO

SELECT 
	DEPTO, 
	CARGO,
	COUNT(*)		AS QTD_EMPREGADOS,
	SUM(SALARIO)	AS TOT_SALARIO,
	AVG(SALARIO)	AS MED_SALARIO,
	PERCENTILE_DISC(0.5) WITHIN GROUP (ORDER BY SALARIO)  
        OVER (PARTITION BY DEPTO,CARGO) AS MedianDisc 
FROM TB_EMPREGADO 
	JOIN TB_DEPARTAMENTO 
		ON TB_EMPREGADO.COD_DEPTO = TB_DEPARTAMENTO.COD_DEPTO
	JOIN TB_CARGO
		ON TB_EMPREGADO.COD_CARGO = TB_CARGO.COD_CARGO
GROUP BY DEPTO, CARGO

SELECT DISTINCT 
	DEPTO,CARGO
	,PERCENTILE_DISC(0.5) WITHIN GROUP (ORDER BY SALARIO) OVER (PARTITION BY DEPTO,CARGO) AS MEDIANA
FROM TB_EMPREGADO 
	JOIN TB_DEPARTAMENTO 
		ON TB_EMPREGADO.COD_DEPTO = TB_DEPARTAMENTO.COD_DEPTO
	JOIN TB_CARGO
		ON TB_EMPREGADO.COD_CARGO = TB_CARGO.COD_CARGO

-- DEPARTAMENTOS QUE GASTAM MAIS DE 10000 COM SALARIOS
SELECT 
	DEPTO, 
	SUM(SALARIO)	AS TOT_SALARIO
FROM TB_EMPREGADO JOIN 
	TB_DEPARTAMENTO ON TB_EMPREGADO.COD_DEPTO = TB_DEPARTAMENTO.COD_DEPTO

GROUP BY DEPTO
HAVING SUM(SALARIO) > 10000

SELECT 
	DEPTO, 
	SUM(SALARIO)	AS TOT_SALARIO
FROM TB_EMPREGADO JOIN 
	TB_DEPARTAMENTO ON TB_EMPREGADO.COD_DEPTO = TB_DEPARTAMENTO.COD_DEPTO
WHERE SALARIO > 10000
GROUP BY DEPTO






