SELECT C.NOME AS CLIENTE, PR.DESCRICAO AS PRODUTO, 
	SUM(I.QUANTIDADE) QTD_PRODUTOS_COMPRADOS 
FROM TB_CLIENTE C 
JOIN TB_PEDIDO P ON C.CODCLI = P.CODCLI 
JOIN TB_ITENSPEDIDO I ON I.NUM_PEDIDO = P.NUM_PEDIDO 
JOIN TB_PRODUTO PR ON I.ID_PRODUTO = PR.ID_PRODUTO 
GROUP BY PR.DESCRICAO, C.NOME ORDER BY C.NOME

-----------------------------------------------------------
SELECT C.NOME AS CLIENTE, PR.DESCRICAO AS PRODUTO, 
	SUM(I.QUANTIDADE) QTD_PRODUTOS_COMPRADOS 
FROM TB_CLIENTE C 
JOIN TB_PEDIDO P ON C.CODCLI = P.CODCLI 
JOIN TB_ITENSPEDIDO I ON I.NUM_PEDIDO = P.NUM_PEDIDO 
JOIN TB_PRODUTO PR ON I.ID_PRODUTO = PR.ID_PRODUTO 
GROUP BY C.NOME, PR.DESCRICAO ORDER BY C.NOME

-------------------------------------------------------
SELECT CLIENTE.NOME, COUNT(*) AS QTD_PEDIDOS FROM CLIENTE 
JOIN PEDIDO ON CLIENTE.CODCLI = PEDIDO.CODCLI 
WHERE MONTH(PEDIDO.DATA) = 1 
GROUP BY CLIENTE.NOME 
HAVING COUNT(*) > 100;