USE BD_ANAC

SELECT * FROM TB_AERODROMO
SELECT * FROM TB_EMPRESA
SELECT * FROM TB_JUSTIFICATIVA
SELECT * FROM TB_TIPO_LINHA
SELECT * FROM TB_TIPO_VOO
SELECT * FROM TB_VOO
---------------------------------------------------------------------------------------
-- QUAL A DURAÇÃO REAL MÉDIA (EM MINUTOS) DOS VOOS REALIZADOS 
-- ENTRE A CIDADE DE SÃO PAULO (ORIGEM) E A CIDADE DO RIO DE JANEIRO (DESTINO)?

SELECT 
	AVG(DATEDIFF(MINUTE, DT_HR_PARTIDA_REAL, DT_HR_CHEGADA_REAL)) AS [DURAÇÃO MÉDIA DOS VOOS DE SP A RJ EM MINUTOS]
FROM TB_VOO 
WHERE ID_AERODROMO_ORIGEM IN (SELECT ID FROM TB_AERODROMO WHERE NM_CIDADE = 'SÃO PAULO') AND 
      ID_AERODROMO_DESTINO IN (SELECT ID FROM TB_AERODROMO WHERE NM_CIDADE = 'RIO DE JANEIRO')
---------------------------------------------------------------------------------------
-- QUAL A EMPRESA QUE POSSUI A MAIOR MÉDIA DE ATRASADO NA CHEGADA?

SELECT TOP 1
	TB_EMPRESA.NM_EMPRESA AS [NOME DA EMPRESA],
	AVG(DATEDIFF(MINUTE, DT_HR_CHEGADA_PREVISTA, DT_HR_CHEGADA_REAL)) AS [MÉDIA DE ATRASADO NA CHEGADA]
FROM TB_EMPRESA 
JOIN TB_VOO ON TB_VOO.ID_EMPRESA = TB_EMPRESA.ID
GROUP BY TB_EMPRESA.NM_EMPRESA
ORDER BY [MÉDIA DE ATRASADO NA CHEGADA] DESC
---------------------------------------------------------------------------------------
-- QUAL O AEROPORTO (AERÓDROMOS) DE ORIGEM QUE TEVE O MAIOR PERCENTUAL DE 
-- VOOS, CLASSIFICADOS COMO REGULARES, CANCELADOS (QUANTIDADE DE VOOS 
-- CANCELADOS/ QUANTIDADE TOTAL DE VOOS), CONSIDERE APENAS OS AEROPORTOS 
-- COM MAIS DE 5 MIL VOOS REGULARES.
SELECT ID_AERODROMO_ORIGEM AS [AERÓDROMO],
	   COUNT(ID_AERODROMO_ORIGEM) AS [QTD VÔOS CANCELADOS]
FROM TB_VOO
WHERE ID_JUSTIFICATIVA IN (
			SELECT ID FROM TB_JUSTIFICATIVA WHERE DS_JUSTIFICATIVA LIKE 'CANCELA%'
			) AND
      ID_AERODROMO_ORIGEM IN (
			SELECT ID_AERODROMO_ORIGEM FROM TB_VOO 
            GROUP BY ID_AERODROMO_ORIGEM HAVING COUNT(ID_AERODROMO_ORIGEM) > 5000
			) AND
      ID_TIPO_VOO = 0
GROUP BY ID_AERODROMO_ORIGEM
ORDER BY COUNT(ID_AERODROMO_ORIGEM)
------
SELECT ID_AERODROMO_ORIGEM AS [AERÓDROMO],
	   COUNT(ID_AERODROMO_ORIGEM) AS [QTD VÔOS]
FROM TB_VOO
WHERE ID_AERODROMO_ORIGEM IN (
			SELECT ID_AERODROMO_ORIGEM FROM TB_VOO 
            GROUP BY ID_AERODROMO_ORIGEM HAVING COUNT(ID_AERODROMO_ORIGEM) > 5000
			) AND
      ID_TIPO_VOO = 0
GROUP BY ID_AERODROMO_ORIGEM
ORDER BY COUNT(ID_AERODROMO_ORIGEM)


-- QUAL O AEROPORTO DE ORIGEM NO BRASIL COM A MAIOR QUANTIDADE DE VOOS, QUE SÓ ATUOU COM VOOS COM SERVIÇO DE TIPO DE LINHA MISTA 
-- (NÃO TEVE VOOS COM COM SERVIÇO DE TIPO DE LINHA CARGUEIRA)? * --

Select * from TB_TIPO_LINHA



SELECT ID_AERODROMO_ORIGEM AS [AERÓDROMO],
	   COUNT(ID_AERODROMO_ORIGEM) AS [QTD VÔOS CANCELADOS]
FROM TB_VOO
WHERE ID_JUSTIFICATIVA IN (
			SELECT ID FROM TB_JUSTIFICATIVA WHERE DS_JUSTIFICATIVA LIKE 'CANCELA%'
			) AND
      ID_AERODROMO_ORIGEM IN (
			SELECT ID_AERODROMO_ORIGEM FROM TB_VOO 
            GROUP BY ID_AERODROMO_ORIGEM HAVING COUNT(ID_AERODROMO_ORIGEM) > 5000
			) AND
      ID_TIPO_VOO = 0
GROUP BY ID_AERODROMO_ORIGEM
ORDER BY ID_AERODROMO_ORIGEM

SELECT ID_AERODROMO_ORIGEM AS [AERÓDROMO],
	   COUNT(ID_AERODROMO_ORIGEM) AS [QTD VÔOS]
FROM TB_VOO
WHERE ID_AERODROMO_ORIGEM IN (
			SELECT ID_AERODROMO_ORIGEM FROM TB_VOO 
            GROUP BY ID_AERODROMO_ORIGEM HAVING COUNT(ID_AERODROMO_ORIGEM) > 5000
			) AND
      ID_TIPO_VOO = 0
GROUP BY ID_AERODROMO_ORIGEM
ORDER BY ID_AERODROMO_ORIGEM
